# Generated by Django 5.2.9 on 2025-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenmanager",
            name="popular_times",
            field=models.JSONField(
                blank=True,
                help_text="Popular times data for foot traffic analysis",
                null=True,
            ),
        ),
    ]
