# Generated by Django 5.2.9 on 2025-12-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_screenmanager_popular_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanager",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
