# Generated by Django 5.2.9 on 2025-12-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_adsmanager_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsmanager",
            name="involve_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adsmanager",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]
